#!/usr/bin/env node
// Compile the design system's Tailwind v4 stylesheet into a static CSS file for
// the design-sync bundle. The raw globals.css only declares tokens + `@import
// "tailwindcss"`; this run resolves every utility class used by the components
// and the authored previews into real CSS, plus the :root/.dark token sets.
// Output is gitignored cache; regenerated by cfg.buildCmd before each converter run.
import postcss from "@tailwindcss/postcss";
import postcssProcessor from "postcss";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));        // .../web/frontend/.design-sync
const root = resolve(here, "..");                            // .../web/frontend
const input = resolve(here, "tw-input.css");
const outDir = resolve(here, ".cache");
const out = resolve(outDir, "compiled.css");

mkdirSync(resolve(here, "previews"), { recursive: true });   // @source target must exist
mkdirSync(outDir, { recursive: true });

const css = readFileSync(input, "utf8");
const result = await postcssProcessor([postcss()]).process(css, { from: input, to: out });
writeFileSync(out, result.css);
console.error(`[build-css] wrote ${out} (${result.css.length} bytes)`);
