#!/usr/bin/env node
// Generate the design-sync bundle entry. The app ships no library dist, so we
// synthesize a barrel that re-exports every component module under src/components
// (via the `@/` alias, resolved by esbuild from tsconfig). This makes every
// component AND its compound sub-parts available on window.<globalName> at
// runtime; which of them get preview cards is decided by cfg.componentSrcMap.
// Output is gitignored cache; regenerated by cfg.buildCmd before each converter run.
import { readdirSync, writeFileSync, mkdirSync, statSync } from "node:fs";
import { resolve, dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));   // .../web/frontend/.design-sync
const root = resolve(here, "..");                       // .../web/frontend
const srcDir = resolve(root, "src/components");
const outDir = resolve(here, ".cache");
const out = resolve(outDir, "entry.tsx");

const SKIP = /\.(test|spec|stories)\.(tsx|jsx)$/;
const files = [];
(function walk(dir) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (/\.(tsx|jsx)$/.test(e.name) && !SKIP.test(e.name)) files.push(p);
  }
})(srcDir);

files.sort();
// src/components/ui/button.tsx -> @/components/ui/button
const alias = (p) => "@/" + relative(resolve(root, "src"), p).replace(/\\/g, "/").replace(/\.(tsx|jsx)$/, "");
const body =
  "// AUTO-GENERATED by .design-sync/build-entry.mjs — do not edit.\n" +
  files.map((p) => `export * from ${JSON.stringify(alias(p))};`).join("\n") +
  "\n" +
  // Re-export sonner's imperative `toast` so it shares the bundled Toaster's
  // sonner instance (previews and the design agent can fire toasts via it).
  'export { toast } from "sonner";\n';

mkdirSync(outDir, { recursive: true });
writeFileSync(out, body);
console.error(`[build-entry] wrote ${out} (${files.length} modules)`);
